### ISSUE TITLE
PointerId

### ISSUE THREAD

**Issue by nomve** [mkalten/TUIO20_CPP#6]
Hi,

I have a question regarding component IDs of Tuio2 pointers. The specification says:

> it defines a Component ID that allows the distinction of individual pointer components during a whole session.

However, in TuioClient, you initialise the pointer like so

` new TuioPointer(frameTime,tobj,t_id,u_id,c_id,xpos,ypos,angle,shear,radius,pressure);`

where c_id is actually the pointer_id of TuioPointer. So my questions are, is component id the same as pointer id, and what is its actual purpose? I see the explanation, but don't really get it.

**Comment by mkalten** [comment]
yes, the component id is equivalent to the pointer id in this case, I just used that term for all components ids such as token ids and pointers ids.
