### ISSUE TITLE
Won't build?

### ISSUE THREAD

**Issue by Dijuna** [mkalten/TUIO20_CPP#7]
1>------ Build started: Project: libTUIO2, Configuration: Release Win32 ------
1>  IpEndpointName.cpp
1>  NetworkingUtils.cpp
1>  UdpSocket.cpp
1>  OscOutboundPacketStream.cpp
1>  OscPrintReceivedElements.cpp
1>  OscReceivedElements.cpp
1>  OscTypes.cpp
1>  FlashSender.cpp
1>  OscReceiver.cpp
**1>  TcpReceiver.cpp
1>..\TUIO2\TcpReceiver.cpp(30): error C2371: 'int32_t': redefinition; different basic types
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h(19): note: see declaration of 'int32_t'**
1>  TcpSender.cpp
1>  TuioBounds.cpp
1>  TuioClient.cpp
1>  TuioComponent.cpp
1>  TuioDispatcher.cpp
1>  TuioManager.cpp
1>  TuioObject.cpp
1>  TuioPoint.cpp
1>  TuioPointer.cpp
1>  TuioServer.cpp
1>  Compiling...
1>  TuioSymbol.cpp
1>  TuioTime.cpp
1>  TuioToken.cpp
1>  UdpReceiver.cpp
1>  UdpSender.cpp
1>  WebSockSender.cpp
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Dijuna** [comment]
had to remove TcpReceiver.h/.cpp from project

**Comment by mkalten** [comment]
thanks for the heads up, I just pushed an according fix.
please let me know if this works for you ...
